

#===============================================================================
#   dsFreda Internal Auxiliary Functions
#===============================================================================


#===============================================================================
#' AssertIfNotNull
#'
#' Wrapper around \code{assertthat::assert_that()} for arguments that are set to NULL by default (e.g. optional arguments)
#'
#' @param Argument The function argument that should be checked if it is not NULL
#' @param CheckFunction \code{function} or \code{list} - A function or a list of functions suited to check a condition demanded of the argument (like \code{is.character})
#' @return NULL
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
AssertIfNotNull <- function(Argument,
                            CheckFunction)
#-------------------------------------------------------------------------------
{
  require(assertthat)

  if (!is.null(Argument))
  {
      if (!is.list(CheckFunction)) { CheckFunction <- list(CheckFunction) }   # In case 'CheckFunction' contains only a single function, convert it into a list for syntax reasons

      # Go through each element in list 'CheckFunction', construct/parse an assert_that-call and evaluate it
      for (i in 1:length(CheckFunction))
      {
          eval(parse(text = paste0("assertthat::assert_that(",
                                   deparse(substitute(CheckFunction[[i]])),
                                   "(",
                                   deparse(substitute(Argument)), "))")),
               envir = parent.frame())
      }
  }

  return(NULL)
}
#===============================================================================


#===============================================================================
#' GetClass
#'
#' Wrapper around \code{base::class()} with more informative output
#'
#' @param Object Arbitrary R object
#' @return \code{string}
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
GetClass <- function(Object)
{
  Class <- class(Object)[1]      # Some objects return more than one string as class info (e.g. ResourceClient objects). Take only first string for these cases.

  if (tibble::is_tibble(Object)) { Class <- "tibble" }

  return(Class)
}
#===============================================================================


#===============================================================================
#' .get_encode_dictionary
#'
#' Taken from dsTidyverse package. Generate an encoding key which is used for encoding and decoding strings to pass the R parser
#'
#' @return A list containing the encoding key, with 'input' specifying the characters to be encoded
#' and 'output' specifying their corresponding encoded values.
#' @keywords internal
#' @noRd
.get_encode_dictionary <- function()
{
  encode_list <- list(input = c("(", ")", "\"", ",", " ", "!", "&", "|", "'", "=", "+", "-", "*", "/", "^", ">", "<", "~", "\n", "%in%"),
                      output = c("$LB$", "$RB$", "$QUOTE$", "$COMMA$", "$SPACE$", "$EXCL$", "$AND$", "$OR$",
                                 "$APO$", "$EQU$", "$ADD$", "$SUB$", "$MULT$", "$DIVIDE$", "$POWER$", "$GT$", "$LT$", "$TILDE$", "$LINE$", "$IN$"))

  return(encode_list)
}


#' Encode a string using the provided encoding key.
#'
#' @param input_string The string to be encoded.
#' @param encode_key The encoding key generated by '.get_encode_dictionary()'.
#' @return The encoded string.
#' @keywords internal
#' @noRd
.encode_tidy_eval <- function(input_string, encode_key)
{
  encode_vec <- encode_key$output
  names(encode_vec) <- encode_key$input
  split_string <- strsplit(input_string, "")[[1]]
  output_string <- sapply(split_string,
                          function(char)
                          {
                              if (char %in% names(encode_vec))
                              { encode_vec[[char]]
                              } else { char }
                          })
  return(paste(output_string, collapse = ""))
}


#' Decode a string using the provided encoding key.
#'
#' @param input_string The encoded string passed through the R parser.
#' @param encode_key The encoding key generated by '.get_encode_dictionary()'.
#' @return The decoded string.
#' @keywords internal
#' @noRd
.decode_tidy_eval <- function(input_string, encode_key)
{
  encode_vec <- encode_key$input
  names(encode_vec) <- encode_key$output

  output_string <- Reduce(function(out, pattern)
                          {
                              gsub(pattern, encode_vec[[pattern]], out, fixed = TRUE)
                          }, names(encode_vec), input_string)
  return(output_string)
}
#===============================================================================


#===============================================================================
#' PrintSoloMessage
#'
#' Print text passed in a one-dimensional (named) character vector. Optionally add symbols and specific formatting based on vector element name.
#'
#' @param message \code{character vector} of length 1 with optional name
#' @export
#-------------------------------------------------------------------------------
PrintSoloMessage <- function(message)
#-------------------------------------------------------------------------------
{
  if (names(message) == "Topic")
  {
      # Print topic string in bold letters (formatted with ANSI code \033...) and with horizontal line underneath
      cat("\033[1m", as.character(message), "\n", paste0(rep("~", times = stringr::str_length(as.character(message))), collapse = ""), "\033[0m", "\n", sep = "")

  } else {

      cli::cat_bullet(as.character(message),
                      bullet = dplyr::case_when(names(message) == "Info" ~ "info",
                                                names(message) == "Success" ~ "tick",
                                                names(message) == "Warning" ~ "warning",
                                                names(message) == "Failure" ~ "cross",
                                                TRUE ~ "none"),
                      bullet_col = dplyr::case_when(names(message) == "Success" ~ dsFredaClient::FredaColors$Green,
                                                    names(message) == "Warning" ~ dsFredaClient::FredaColors$Orange,
                                                    names(message) == "Failure" ~ dsFredaClient::FredaColors$Red,
                                                    TRUE ~ "black"))
  }
}


#===============================================================================
#' PrintMessages
#'
#' Take list of messages and print them with \code{PrintSoloMessage()}.
#'
#' @param Messages \code{list} List of of named vectors
#' @export
#-------------------------------------------------------------------------------
PrintMessages <- function(Messages)
#-------------------------------------------------------------------------------
{
  purrr::walk(.x = Messages,
              .f = function(Subvector)      # List of messages contains named vectors that serve as 'topic-specific messages'
                   {
                        cat("\n")

                        for (i in 1:length(Subvector))      # for-loop instead of nested purrr::walk because items in list are vectors
                        {
                            PrintSoloMessage(Subvector[i])
                        }

                        cat("\n")
                   })
}
#===============================================================================


#===============================================================================

# Custom Infix Operator %notin%
#' @noRd
#' @export
'%notin%' <- function(x, y) { !(x %in% y) }

#===============================================================================
