

#===============================================================================
#   dsFreda Internal Auxiliary Functions
#===============================================================================


#===============================================================================
#' AssertIfNotNull
#'
#' Wrapper around \code{assertthat::assert_that()} for arguments that are set to NULL by default (e.g. optional arguments)
#'
#' @param Argument The function argument that should be checked if it is not NULL
#' @param CheckFunction \code{function} or \code{list} - A function or a list of functions suited to check a condition demanded of the argument (like \code{is.character})
#' @return NULL
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
AssertIfNotNull <- function(Argument,
                            CheckFunction)
#-------------------------------------------------------------------------------
{
  require(assertthat)

  if (!is.null(Argument))
  {
      if (!is.list(CheckFunction)) { CheckFunction <- list(CheckFunction) }   # In case 'CheckFunction' contains only a single function, convert it into a list for syntax reasons

      # Go through each element in list 'CheckFunction', construct/parse an assert_that-call and evaluate it
      for (i in 1:length(CheckFunction))
      {
          eval(parse(text = paste0("assertthat::assert_that(",
                                   deparse(substitute(CheckFunction[[i]])),
                                   "(",
                                   deparse(substitute(Argument)), "))")),
               envir = parent.frame())
      }
  }

  return(NULL)
}
#===============================================================================


#===============================================================================
#' GetClass
#'
#' Wrapper around \code{base::class()} with more informative output
#'
#' @param Object Arbitrary R object
#' @return \code{string}
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
GetClass <- function(Object)
{
  Class <- class(Object)[1]      # Some objects return more than one string as class info (e.g. ResourceClient objects). Take only first string for these cases.

  if (tibble::is_tibble(Object)) { Class <- "tibble" }

  return(Class)
}
#===============================================================================


#===============================================================================
#' .get_encode_dictionary
#'
#' Taken from dsTidyverse package. Generate an encoding key which is used for encoding and decoding strings to pass the R parser
#'
#' @return A list containing the encoding key, with 'input' specifying the characters to be encoded
#' and 'output' specifying their corresponding encoded values.
#' @keywords internal
#' @noRd
.get_encode_dictionary <- function()
{
  encode_list <- list(input = c("(", ")", "\"", ",", " ", "!", "&", "|", "'", "=", "+", "-", "*", "/", "^", ">", "<", "~", "\n", "%in%"),
                      output = c("$LB$", "$RB$", "$QUOTE$", "$COMMA$", "$SPACE$", "$EXCL$", "$AND$", "$OR$",
                                 "$APO$", "$EQU$", "$ADD$", "$SUB$", "$MULT$", "$DIVIDE$", "$POWER$", "$GT$", "$LT$", "$TILDE$", "$LINE$", "$IN$"))

  return(encode_list)
}


#' Encode a string using the provided encoding key.
#'
#' @param input_string The string to be encoded.
#' @param encode_key The encoding key generated by '.get_encode_dictionary()'.
#' @return The encoded string.
#' @keywords internal
#' @noRd
.encode_tidy_eval <- function(input_string, encode_key)
{
  encode_vec <- encode_key$output
  names(encode_vec) <- encode_key$input
  split_string <- strsplit(input_string, "")[[1]]
  output_string <- sapply(split_string,
                          function(char)
                          {
                              if (char %in% names(encode_vec))
                              { encode_vec[[char]]
                              } else { char }
                          })
  return(paste(output_string, collapse = ""))
}


#' Decode a string using the provided encoding key.
#'
#' @param input_string The encoded string passed through the R parser.
#' @param encode_key The encoding key generated by '.get_encode_dictionary()'.
#' @return The decoded string.
#' @keywords internal
#' @noRd
.decode_tidy_eval <- function(input_string, encode_key)
{
  encode_vec <- encode_key$input
  names(encode_vec) <- encode_key$output

  output_string <- Reduce(function(out, pattern)
                          {
                              gsub(pattern, encode_vec[[pattern]], out, fixed = TRUE)
                          }, names(encode_vec), input_string)
  return(output_string)
}
#===============================================================================


#===============================================================================
#' Log.New
#'
#' Initiate a log report \code{tibble} with one or multiple entries
#'
#' @return A \code{tibble}
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
Log.New <- function(Table = NULL,
                    ProcessingStage = NULL,
                    ProcessTopic = NULL,
                    ProcessExecution = NULL,
                    ReportType = "Message",
                    DetailsGroup = NULL,
                    CountRootSubjects.Affected = NULL,
                    CountRootSubjects.Removed = NULL,
                    CountRootSubjects.Current = NULL,
                    CountRecords.Affected = NULL,
                    CountRecords.Removed = NULL,
                    CountRecords.Added = NULL,
                    CountRecords.Current = NULL,
                    Message = NULL,
                    MessageClass = "Info",
                    MessagePriority = 1L,
                    Timestamp = Sys.time(),
                    PrintMessage = FALSE)
#-------------------------------------------------------------------------------
{
  if (length(Table) > 0) { assert_that(is.character(Table)) }
  if (length(ProcessingStage) > 0) { assert_that(is.character(ProcessingStage)) }
  if (length(ProcessTopic) > 0) { assert_that(is.character(ProcessTopic)) }
  if (length(ProcessExecution) > 0) { assert_that(is.character(ProcessExecution)) }
  if (length(ReportType) > 0) { assert_that(is.character(ReportType)) }
  if (length(DetailsGroup) > 0) { assert_that(is.character(DetailsGroup)) }
  if (length(CountRootSubjects.Affected) > 0) { assert_that(is.numeric(CountRootSubjects.Affected)) }
  if (length(CountRootSubjects.Removed) > 0) { assert_that(is.numeric(CountRootSubjects.Removed)) }
  if (length(CountRootSubjects.Current) > 0) { assert_that(is.numeric(CountRootSubjects.Current)) }
  if (length(CountRecords.Affected) > 0) { assert_that(is.numeric(CountRecords.Affected)) }
  if (length(CountRecords.Removed) > 0) { assert_that(is.numeric(CountRecords.Removed)) }
  if (length(CountRecords.Added) > 0) { assert_that(is.numeric(CountRecords.Added)) }
  if (length(CountRecords.Current) > 0) { assert_that(is.numeric(CountRecords.Current)) }
  if (length(Message) > 0) { assert_that(is.character(Message)) }
  if (length(MessageClass) > 0) { assert_that(is.character(MessageClass)) }
  if (length(MessagePriority) > 0) { assert_that(is.numeric(MessagePriority)) }
  if (length(Timestamp) > 0) { assert_that(is.time(Timestamp)) }

  Log <- tibble(Table = ifelse(!is.null(Table), Table, character()),
                ProcessingStage = ifelse(!is.null(ProcessingStage), ProcessingStage, character()),
                ProcessTopic = ifelse(!is.null(ProcessTopic), ProcessTopic, character()),
                ProcessExecution = ifelse(!is.null(ProcessExecution), ProcessExecution, character()),
                ReportType = ifelse(!is.null(ReportType), ReportType, character()),
                DetailsGroup = ifelse(!is.null(DetailsGroup), DetailsGroup, character()),
                CountRootSubjects.Affected = ifelse(!is.null(CountRootSubjects.Affected), CountRootSubjects.Affected, numeric()),
                CountRootSubjects.Removed = ifelse(!is.null(CountRootSubjects.Removed), CountRootSubjects.Removed, numeric()),
                CountRootSubjects.Current = ifelse(!is.null(CountRootSubjects.Current), CountRootSubjects.Current, numeric()),
                CountRecords.Affected = ifelse(!is.null(CountRecords.Affected), CountRecords.Affected, numeric()),
                CountRecords.Removed = ifelse(!is.null(CountRecords.Removed), CountRecords.Removed, numeric()),
                CountRecords.Added = ifelse(!is.null(CountRecords.Added), CountRecords.Added, numeric()),
                CountRecords.Current = ifelse(!is.null(CountRecords.Current), CountRecords.Current, numeric()),
                Message = ifelse(!is.null(Message), Message, character()),
                MessageClass = ifelse(!is.null(MessageClass), MessageClass, "Info"),
                MessagePriority = ifelse(!is.null(MessagePriority), MessagePriority, 1),
                Timestamp = as.POSIXct(ifelse(!is.null(Timestamp), Timestamp, Sys.time())))

  if (PrintMessage == TRUE) { Log.Print(Log) }

  return(Log)
}

#-------------------------------------------------------------------------------

#' Log.Add
#'
#' Add one or more records to an existing log data.frame and optionally print messages in the process.
#'
#' @param Log \code{data.frame} - An existing log.
#' @param Entry \code{data.frame} - New log entry
#' @param PrintMessage \code{logical flag} - Whether to print the messages contained in 'LogEntry'
#' @return The updated log \code{data.frame}
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
Log.Add <- function(Log,
                    Entry,
                    PrintMessage = FALSE)
#-------------------------------------------------------------------------------
{
  assert_that(is.data.frame(Log),
              is.data.frame(Entry),
              is.flag(PrintMessage))

  Log <- Log %>%
            bind_rows(Entry) %>%
            fill(ProcessingStage,      # Adopt values from previous rows
                 .direction = "down")

  if (PrintMessage == TRUE) { Log.Print(Entry) }

  return(Log)
}

#-------------------------------------------------------------------------------

#' Log.Make
#'
#' Turn a data.frame with some properties of a log entry into a full log entry
#'
#' @param LogData \code{data.frame} - data on new log entries
#' @param PrintMessage \code{logical flag} - Whether messages should be printed to console
#' @return A \code{data.frame} containing full log entry properties
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
Log.Make <- function(LogData,
                     PrintMessage = FALSE)
#-------------------------------------------------------------------------------
{
  assert_that(is.data.frame(LogData))
  assert_that(is.flag(PrintMessage))

  Log <- do.call(Log.New, args = c(as.list(LogData), PrintMessage = PrintMessage))

  return(Log)
}

#-------------------------------------------------------------------------------

#' Log.Print
#'
#' Print messages contained in a log report data.frame
#'
#' @param LogData \code{data.frame} - Log report data.frame
#' @return No return
#' @keywords internal
#' @noRd
#-------------------------------------------------------------------------------
Log.Print <- function(Log)
#-------------------------------------------------------------------------------
{
  assert_that(is.data.frame(Log))

  Messages <- Log %>%
                select(MessageClass,
                       Message) %>%
                tibble::deframe()

  for (i in 1:length(Messages)) { PrintSoloMessage(Messages[i]) }
}
#===============================================================================


#===============================================================================
#' PrintSoloMessage
#'
#' Print text passed in a one-dimensional (named) character vector. Optionally add symbols and specific formatting based on vector element name.
#'
#' @param message \code{character vector} of length 1 with optional name
#' @export
#-------------------------------------------------------------------------------
PrintSoloMessage <- function(message)
#-------------------------------------------------------------------------------
{
  if (names(message) == "Topic")
  {
      # Print topic string in bold letters (formatted with ANSI code \033...) and with horizontal line underneath
      cat("\033[1m", as.character(message), "\n", paste0(rep("~", times = stringr::str_length(as.character(message))), collapse = ""), "\033[0m", "\n", sep = "")

  } else {

      cli::cat_bullet(as.character(message),
                      bullet = dplyr::case_when(names(message) == "Info" ~ "info",
                                                names(message) == "Success" ~ "tick",
                                                names(message) == "Warning" ~ "warning",
                                                names(message) == "Failure" ~ "cross",
                                                names(message) == "Special" ~ "star",
                                                .default = "none"),
                      bullet_col = dplyr::case_when(names(message) == "Success" ~ FredaColors$Green,
                                                    names(message) == "Warning" ~ FredaColors$Orange,
                                                    names(message) == "Failure" ~ FredaColors$Red,
                                                    .default = "black"))
  }
}


#===============================================================================
#' PrintMessages
#'
#' Take list of messages and print them with \code{PrintSoloMessage()}.
#'
#' @param Messages \code{list} List of named vectors
#' @export
#-------------------------------------------------------------------------------
PrintMessages <- function(Messages)
#-------------------------------------------------------------------------------
{
  purrr::walk(.x = Messages,
              .f = function(Subvector)      # List of messages contains named vectors that serve as 'topic-specific messages'
                   {
                        cat("\n")

                        for (i in 1:length(Subvector))      # for-loop instead of nested purrr::walk because items in list are vectors
                        {
                            PrintSoloMessage(Subvector[i])
                        }

                        cat("\n")
                   })
}
#===============================================================================


#===============================================================================

# Custom Infix Operator %notin%
#' @noRd
#' @export
'%notin%' <- function(x, y) { !(x %in% y) }

#===============================================================================
